<?php
return[
    'site_title'=>'Posterat',
    'site_slogan'=>'For Ads',
    'site_description'=>'Sale And Buy On Internet',
    'year'=>'2021',
    'designedby'=> 'Posterat',
    'slider_limit'=>10,
    'pagination'=>5,
    'ads_home_limit'=>36,
    'premium_ad_mark'=>true, //in home page
    'related_ads_limit'=>2, //single ad page
    'lang_code'=>['ar','en'],
    'theme'=> (config('app.locale') == 'ar')?'theme-rtl':'theme',
    'sell'=>'SELL',
    'top'=>'Top',
    'photos-demo'=>'ad-demo/',
    'preloader'=>false,
    'more_ads'=>false,
    'pre_phone'=>'+965',
    'breadcrumb'=> true,
    'map'=> true,
    'sticky_ad_detail'=> false,
    'ad_advice'=>false,
    'last_ads_category'=>false,
    'special_ads_category'=>false,
    'popular_categories'=>false,
    'ad_points'=>3,
    'like_points'=>1,
    'image_prefix'=>'amr_'. rand(1, 9999),
    'tawk_to_chat'=>0,
    'usual_balance'=>5,
    'usual_expired_at'=>30,//days
    'paid_expired_at'=>30,//days
    'payment_mode'=>'live',
    'theme_switcher'=>false,
    'theme_select'=>'default',
    'pages_top_menu'=> 0,
    'slider_height'=> 49,
    'ad_image_height'=> 15,
    'home_per_row'=> 4,
    'create_ad_step1'=>'نشر اعلانا على بدون مقابل! ومع ذلك، يجب على جميع الإعلانات متابعة قواعدنا:',
    'create_ad_step2'=>'نشر اعلانا على بدون مقابل! ومع ذلك، يجب على جميع الإعلانات متابعة قواعدنا:',
    'facebook_link'=>'#',
    'twitter_link'=>'#',
    'instagram_link'=>'#',
    'linkedin_link'=>'#',
    'youtube_link'=>'#',
    'tiktok_link'=>'#',

];
